networks:
  appelephant:
    name: appelephant
services:
  db:
    container_name: elephant_db
    environment:
      POSTGRES_DB: elephant_dev
      POSTGRES_PASSWORD: elephant
      POSTGRES_USER: elephant
    image: postgres:13.5
    networks:
      appelephant: null
    ports:
    - published: 5432
      target: 5432
    restart: always
    sysctls: {}
    volumes: []
  elephant:
    build:
      context: /home/zoedsoupe/documents/appelephant/elephant
    command: mix phx.server
    container_name: elephant
    depends_on:
      db:
        condition: service_started
    environment: {}
    image: elephant:c6jj6xyr9256yj5sslknymf7br1lj7fh
    networks:
      appelephant: null
    ports:
    - published: 4000
      target: 4000
    - published: 4001
      target: 4001
    restart: unless-stopped
    sysctls: {}
    tty: true
    volumes:
    - elephant
version: '3.4'
